version: '2.1'
# Containers
services:
  mirror_c: # Mirror container
    build:
      context: ./Mirror
      dockerfile: Dockerfile
    environment:
      - deps=postgresql,python3 # dependencies
    expose:
      - "8080"

  client_c: # Client container
    build:
      context: ./Client
      dockerfile: Dockerfile
    links:
      - mirror_c
    ports:
      - "8082:8080"
