version: '2'


services:
  mirror:
    image: mirror
    environment:
      - deps="postgresql,python3"
    expose:
      - "8080"

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    depends_on:
      - "mirror"
