version: '2.1'


services:
  client_c:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      mirror_c:
        condition: service_healthy
    links:
      - mirror_c

  mirror_c:
    build:
      context: ./Mirror
      dockerfile: Dockerfile
    environment:
      - deps=postgresql,python3
    expose:
      - "8080"
    healthcheck:
      test: "curl -f http://google.com:80"
      interval: 2s
      timeout: 2s
      retries: 5


